### ISSUE TITLE
Can you provide the pretrained model?

### ISSUE THREAD

**Issue by sumai-1998** [cjeen/sketchsampler#3]
It takes a long time (8 days) for me to train from scratch.

**Comment by cjeen** [comment]
It takes about 3 days on my machine (8 GPUS). Something may be blocking your speed when running. good luck! my pretrained model is uploaded: [https://drive.google.com/file/d/1BCP-BYuEdxIRT0P5m6y_WmDy_LTykctR/view?usp=sharing](https://drive.google.com/file/d/1BCP-BYuEdxIRT0P5m6y_WmDy_LTykctR/view?usp=sharing)

**Comment by sumai-1998** [comment]
> 

Thanks a lot

**Comment by cjeen** [comment]
@sumai-1998 Some keys need to be replaced :
 ```python 

import torch
model = torch.load("sketchsampler.ckpt")
for key in list(model['state_dict'].keys()):
    if key.startswith("g_Feat."):
        model['state_dict'][key.replace("g_Feat.", "sketch_translator.parameter.")] = model['state_dict'][key]
        del model['state_dict'][key]
    if key.startswith("g_Feat2PC."):
        model['state_dict'][key.replace("g_Feat2PC.", "depth_head.")] = model['state_dict'][key]
        del model['state_dict'][key]
    if key.startswith("g_Entropy."):
        model['state_dict'][key.replace("g_Entropy.", "density_head.")] = model['state_dict'][key]
        del model['state_dict'][key]
torch.save(model, "sketchsampler_new.ckpt")
 ```

**Comment by sumai-1998** [comment]
> @sumai-1998 Some keys need to be replaced :
> 
> ```python
> import torch
> model = torch.load("sketchsampler.ckpt")
> for key in list(model['state_dict'].keys()):
>    if key.startswith("g_Feat."):
>        model['state_dict'][key.replace("g_Feat.", "sketch_translator.parameter.")] = model['state_dict'][key]
>        del model['state_dict'][key]
>    if key.startswith("g_Feat2PC."):
>        model['state_dict'][key.replace("g_Feat2PC.", "depth_head.")] = model['state_dict'][key]
>        del model['state_dict'][key]
>    if key.startswith("g_Entropy."):
>        model['state_dict'][key.replace("g_Entropy.", "density_head.")] = model['state_dict'][key]
>        del model['state_dict'][key]
> torch.save(model, "sketchsampler_new.ckpt")
> ```

This is helpful, thanks !

**Comment by hujingyucd** [comment]
Hello, thanks for your help! But when I try to load the "sketchsamper_new.ckpt" use code  model.load_from_checkpoint("sketchsampler_new.ckpt")
It shows 

Traceback (most recent call last):
  File "src/trainval.py", line 139, in main
    run(cfg)
  File "src/trainval.py", line 125, in run
    model.load_from_checkpoint("sketchsampler_new.ckpt")
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 198, in _load_model_state
    model = cls(**_cls_kwargs)
  File "/data/ssd/00_direction_induced/sketchsampler/src/model/sketchsampler.py", line 154, in __init__
    self.n_points = self.cfg.train.n_points
omegaconf.errors.ConfigAttributeError: Key 'n_points' is not in struct
        full_key: train.n_points
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict


It seems that the keys still do not match. Really appreciate it if you can give some suggestions about it. Thanks in advanced!

**Comment by cjeen** [comment]
> Hello, thanks for your help! But when I try to load the "sketchsamper_new.ckpt" use code model.load_from_checkpoint("sketchsampler_new.ckpt") It shows
> 
> Traceback (most recent call last): File "src/trainval.py", line 139, in main run(cfg) File "src/trainval.py", line 125, in run model.load_from_checkpoint("sketchsampler_new.ckpt") File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint model = cls._load_model_state(checkpoint, strict=strict, **kwargs) File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 198, in _load_model_state model = cls(**_cls_kwargs) File "/data/ssd/00_direction_induced/sketchsampler/src/model/sketchsampler.py", line 154, in **init** self.n_points = self.cfg.train.n_points omegaconf.errors.ConfigAttributeError: Key 'n_points' is not in struct full_key: train.n_points reference_type=Optional[Dict[Union[str, Enum], Any]] object_type=dict
> 
> It seems that the keys still do not match. Really appreciate it if you can give some suggestions about it. Thanks in advanced!

@hujingyucd  I have tested this code:
``` python

# Instantiate model
    hydra.utils.log.info(f"Instantiating <{cfg.model._target_}>")
    modelcls = hydra.utils.get_class(cfg.model._target_)
    checkpoint_path = cfg.train.ckpt
    model = modelcls.load_from_checkpoint(checkpoint_path=checkpoint_path, cfg=cfg, strict=False)
    model.freeze()
```
This code should work.

**Comment by hujingyucd** [comment]
Hi, thanks for your response. This code does help to load the pre-trained model, but when it runs into trainer.test(), there comes other bugs as follows. Do you meet the similar problem? Thanks again for the quick reply.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/data/ssd/jingyu/00_direction_induced/moreresults/sketchsampler/src/trainval.py", line 143, in main
    run(cfg)
  File "/data/ssd/jingyu/00_direction_induced/moreresults/sketchsampler/src/trainval.py", line 132, in run
    trainer.test(model=model, datamodule=datamodule)
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 923, in test
    results = self.__test_given_model(model, test_dataloaders)
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in __test_given_model
    results = self.fit(model)
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 511, in fit
    self.pre_dispatch()
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 540, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 84, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 256, in pre_dispatch
    self.configure_ddp()
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 200, in configure_ddp
    **self._ddp_kwargs,
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 479, in __init__
    "DistributedDataParallel is not needed when a module "
  File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 604, in _log_and_throw
    raise err_type(err_msg)
RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by cjeen** [comment]
> Hi, thanks for your response. This code does help to load the pre-trained model, but when it runs into trainer.test(), there comes other bugs as follows. Do you meet the similar problem? Thanks again for the quick reply.
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace. Traceback (most recent call last): File "/data/ssd/jingyu/00_direction_induced/moreresults/sketchsampler/src/trainval.py", line 143, in main run(cfg) File "/data/ssd/jingyu/00_direction_induced/moreresults/sketchsampler/src/trainval.py", line 132, in run trainer.test(model=model, datamodule=datamodule) File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 923, in test results = self.__test_given_model(model, test_dataloaders) File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in __test_given_model results = self.fit(model) File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 511, in fit self.pre_dispatch() File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 540, in pre_dispatch self.accelerator.pre_dispatch() File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 84, in pre_dispatch self.training_type_plugin.pre_dispatch() File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 256, in pre_dispatch self.configure_ddp() File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 200, in configure_ddp **self._ddp_kwargs, File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 479, in **init** "DistributedDataParallel is not needed when a module " File "/data/anaconda3/envs/implicit/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 604, in _log_and_throw raise err_type(err_msg) RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

@hujingyucd Try running without DDP (comment out the DDP line in the configuration yaml)?

**Comment by hujingyucd** [comment]
I try to comment out the DDP line in the configuration yaml, but there is additional errors as follows.


[2023-04-12 11:20:29,183][hydra.utils][INFO] - Instantiating the Trainer
/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:50: UserWarning: You requested multiple GPUs but did not specify a backend, e.g. `Trainer(accelerator="dp"|"ddp"|"ddp2")`. Setting `accelerator="ddp_spawn"` for you.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
[2023-04-12 11:20:29,191][lightning][INFO] - GPU available: True, used: True
TPU available: None, using: 0 TPU cores
[2023-04-12 11:20:29,191][lightning][INFO] - TPU available: None, using: 0 TPU cores
[2023-04-12 11:20:29,193][hydra.utils][INFO] - Starting testing!
[2023-04-12 11:20:30,178][pytorch_lightning.accelerators.gpu][INFO] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
Traceback (most recent call last):
  File "src/trainval.py", line 149, in main
    run(cfg)
  File "src/trainval.py", line 138, in run
    trainer.test(model=model, datamodule=datamodule)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 923, in test
    results = self.__test_given_model(model, test_dataloaders)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in __test_given_model
    results = self.fit(model)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 514, in fit
    self.dispatch()
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 548, in dispatch
    self.accelerator.start_testing(self)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 77, in start_testing
    self.training_type_plugin.start_testing(trainer)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 111, in start_testing
    mp.spawn(self.new_process, **self.mp_spawn_kwargs)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/data/hjy/anaconda3/envs/implicit/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TorchHistory.add_log_hooks_to_pytorch_module.<locals>.<lambda>'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by cjeen** [comment]
> You requested multiple GPUs but did not specify a backend

@hujingyucd assign single gpu id?

**Comment by hujingyucd** [comment]
Hi,
    Thanks for your suggestions. I can get the results by running your pre-trained model. However, I find that the predicted point cloud are not aligned.

![image](https://user-images.githubusercontent.com/37215101/231351666-e0f43dcc-39f0-47fd-a26c-561e1aec55ce.png)
![image](https://user-images.githubusercontent.com/37215101/231351694-3d145f26-272f-4d01-853a-2e8541dc3abd.png)


Is there any method to align these predicted point cloud? Thanks again for your help!

**Comment by cjeen** [comment]
> 

@hujingyucd what is the chamfer distance in your results?

**Comment by cjeen** [comment]
> Hi, Thanks for your suggestions. I can get the results by running your pre-trained model. However, I find that the predicted point cloud are not aligned.
> 
> ![image](https://user-images.githubusercontent.com/37215101/231351666-e0f43dcc-39f0-47fd-a26c-561e1aec55ce.png) ![image](https://user-images.githubusercontent.com/37215101/231351694-3d145f26-272f-4d01-853a-2e8541dc3abd.png)
> 
> Is there any method to align these predicted point cloud? Thanks again for your help!

@hujingyucd I assume what you're saying is aligning multiple views of an object, which can be achieved by using camera matrices in the dataset.

**Comment by hujingyucd** [comment]
Can you give more explanations (some example code if possible) on how to achieve this if possible? Since I am not sure about the details, I am afraid I cannot achieve it correctly.

**Comment by cjeen** [comment]
> Can you give more explanations (some example code if possible) on how to achieve this if possible? Since I am not sure about the details, I am afraid I cannot achieve it correctly.

@hujingyucd a possible version using **numpy**:
```python

        # camera coordinate to world corrdinate
        cam_mat, cam_pos = pickle.load(open(camera_path, 'rb'))
        ours_pt = np.dot(ours_pt, cam_mat)

        # normalize aabb
        bbox_ours = np.concatenate([np.min(ours_pt, axis=0, keepdims=True), np.max(ours_pt, axis=0, keepdims=True)], axis=0)
        loc_ours = (bbox_ours[0] + bbox_ours[1]) / 2
        scale_ours = (bbox_ours[1] - bbox_ours[0]).max()

        # transform
        ours_pt -= loc_ours
        ours_pt /= scale_ours
```

**Comment by hujingyucd** [comment]
Got it! Really appreciate your help!
There is just one more question about evaluation. I noticed that you compare your work with Sketch2mesh in all categories. However, it only released its pre-trained model for car and chair and do not released training code. Did you re-implement its code to get its inference results?

**Comment by cjeen** [comment]
> Got it! Really appreciate your help! There is just one more question about evaluation. I noticed that you compare your work with Sketch2mesh in all categories. However, it only released its pre-trained model for car and chair and do not released training code. Did you re-implement its code to get its inference results?

@hujingyucd We retrained their model using their official code on our dataset, and you can refer to the links https://github.com/cvlab-epfl/MeshSDF and https://github.com/cvlab-epfl/sketch2mesh

**Comment by hujingyucd** [comment]
Thanks for your help!

**Comment by XztOK** [comment]
Hello, can you share the code you generated using a pre trained model thanks！
