### ISSUE TITLE
hydra.errors.HydraException

### ISSUE THREAD

**Issue by myang9** [cjeen/sketchsampler#4]
hydra.errors.HydraException: Error calling 'model.sketchsampler.SketchSampler' : Encountered error: `No module named 'cd'` when loading module 'model.sketchsampler.SketchSampler'
Some mistakes about hydra.

**Comment by cjeen** [comment]
It's not about hydra (in this case, hydra just print the error log). It seem to be an error occurred when compiling the module 'cd'. You can debug the line for loading the 'cd' module, or replace it with other chamfer distance implement such as pytorch3d.
